name: "Validate devcontainer-feature.json files"
permissions:
  contents: read
on:
  pull_request:
  merge_group:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: "Validate devcontainer-feature.json files"
        uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772 # v1
        with:
          validate-only: "true"
          base-path-to-features: "./src"
